### PR TITLE
Feature/composer drush

### LINKED ISSUE #103: [trusty] Install composer and drush when creating new box
We should install composer and drush when creating a new box, I can't imagine anybody using a virtual machine with vagrant who doesn't want to use drush. Composer will also be very important for Drupal 8 sites, so having this preinstalled will probably help a lot of people

### PR DESCRIPTION
**Pull request by googletorp**
This installs composer and latest drush stable version. It's possible to configure which drush version you want to install with composer.

I also updated the PHP version in the Vagrantfile, we don't really use this, but seems odd to have the default value be 5.3, so updated it to be 5.5.

This fixes #103

### CODE REVIEW

**Comment by darthsteven** [comment]
@googletorp thanks for the work here! Can you merge in the latest upstream changes to the trusty branch please?

**Comment by googletorp** [comment]
@darthsteven I've updated the branch. It's not needed to merge it in, when github says that the branch has no conflicts though.

**Comment by darthsteven** [comment]
ok to test

**Comment by darthsteven** [comment]
Awesome, looks good to me, thanks!

**Pull request merged**
