### PR TITLE
Update parrot-local.ini.template

### PR DESCRIPTION
**Pull request by tripox**
Update parrot-local.ini.template for better understanding

### CODE REVIEW

**Comment by darthsteven** [comment]
Ah, sorry about that!

We have an internal tool called 'parrot' that runs 'vagrant' in a specific folder on our machines.

**Comment by tripox** [comment]
Ah, nice. :-)
Just thought I would update it to make sure no one got confused.

Can you cherry pick this into master?
I think it's the same there.

**Comment by darthsteven** [comment]
I think we'll just speed onto getting trusty merged into master :)

**Comment by tripox** [comment]
Cool. :-)

**Pull request merged**
